### ISSUE TITLE
Confirmed and Unconfirmed Not Functioning

### ISSUE THREAD

**Issue by jomarip** [theQRL/block-explorer#1]
Under Transactions I could not get the unconfirmed and confirmed buttons to work

**Comment by jplomas** [comment]
The code to display these transactions is not yet build...

**Comment by bcduddupudi** [comment]
When do we get wallet to store the trading coins ,i nvested too much money  in it i don't want to lose it saving in exchanges which are prone to hacks

**Comment by surg0r** [comment]
Whilst QRL is an ERC20 token @bcduddupudi you can store the tokens safely using MyEtherWallet.com or using a hardware wallet such as Ledger Nano S.

Upon mainnet launch we will have functioning code to create offline paper wallet cold storage, the node implementation and a web wallet which is functionally similar to MEW.
