### ISSUE TITLE
pagination in show transaction page

### ISSUE THREAD

**Issue by htobenothing** [theQRL/block-explorer#10]
instead of load all the transaction wait long time(around 10 second) for page to load, better to use pagination. so that can improve the load speed of page. will be user friendly, and can also deal with increment of transaction. 

can refer to the URL below
http://qrlexplorer.info/a/Qc884d7eeb15c7abcdadfdca68bee67c19a5c7e0b98d87fb2bed3b0f18bf80c9025599950

**Comment by jplomas** [comment]
Thanks @htobenothing - Pagination will be added as server-side cacheing of transactions is added, which should massively increase page load time.

**Comment by jplomas** [comment]
Improvement added in 11da473

**Comment by jplomas** [comment]
Improvement added in 11da473
