### ISSUE TITLE
Addresses with large amounts of transactions will not load

### ISSUE THREAD

**Issue by som-dev** [theQRL/block-explorer#209]
I tried viewing the address: Q0106002c7fafa78ed8cf6faabb62ab9d84449bf83ee1f556c34f959a173cc9c3d8bc2fec798158
using the mainnet block explorer and it kept spinning with the "Just a moment... transaction history loading" message.
I spun up my own block-explorer and tried it again.  I noticed the following error message coming from the block-explorer:
I20181010-12:07:58.378(-5)? **ERROR/getAddressState**  [Timestamp: Wed, 10 Oct 2018 17:07:58 GMT] Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4532290 vs. 4194304)

Certainly an easy fix is to increase the grpc message size.  Long-term, this issue would keep reoccurring as the block chain grows, maybe there is planned pagination support for transactions.

**Comment by jplomas** [comment]
Paginated API renders this amenable to fixing in v1 and v2

**Comment by jplomas** [comment]
Implemented in Testnet & will be go live in next release of mainnet node for the upcoming hard fork
