### ISSUE TITLE
Recent blocks should show QRL per block rather than block-reward

### ISSUE THREAD

**Issue by surg0r** [theQRL/block-explorer#213]
The front page of the explorer lists blocks and transactions. 

In my view instead of wasting a significant part of this space displaying a block-reward for each block,  below the number of transactions in the block what should be displayed is: total number of QRL transacted in the block i.e. sum of coinbase + any other transaction amounts.

**Comment by scottdonaldau** [comment]
Change implemented in https://github.com/theQRL/block-explorer/pull/214
