### ISSUE TITLE
Click on 'TOKEN CREATION TRANSACTION' does not change page until page refresh

### ISSUE THREAD

**Issue by doctor-gonzo** [theQRL/block-explorer#23]
Using Chrome Browser, although I think this is related somehow to the issue with the QR codes not updating until refresh (wallet issue #132):

When clicking on a transaction involving a QRT from the QRL explorer homepage, you are taken to a page detailing the transaction. Underneath the token name is the link TOKEN CREATION TRANSACTION

Clicking that link visibly changes the URL in the web browser, but the page itself does not change. After refreshing you arrive on the page with the token creation details

[A gif of the issue](https://gfycat.com/AngryFirmBluejay)

**Comment by scottdonaldau** [comment]
Thanks for reporting this @doctor-gonzo We've got this on our list to sort out

**Comment by scottdonaldau** [comment]
This issue has been resolved.
