### ISSUE TITLE
Info graph is distorted!

### ISSUE THREAD

**Issue by Ompanime** [theQRL/block-explorer#35]
Upon going to the block explorer's main page, the info graph on the top-right side of the page is distorted--only filling up half of the top-half portion of the space that was intended for it.

**Comment by scottdonaldau** [comment]
@Ompanime Is this still an issue for you? Can you please provide screenshots, browser and OS information?

**Comment by jleni** [comment]
I think we can close this

**Comment by jplomas** [comment]
We should probably remove the graph on mobile and just display stats

**Comment by BSGVPG** [comment]
Latest transactions lower down the page are also distorted

**Comment by BSGVPG** [comment]
If you use the same navigation as the the qrl homepage, u will release 30% of the screen.this applies to the explorer and wallet

**Comment by scottdonaldau** [comment]
Mobile view has resolved this.
