### ISSUE TITLE
Block explorer tx history limited to 31 pages

### ISSUE THREAD

**Issue by baudje** [theQRL/block-explorer#36]
Go into block explorer tx history for a certain address (e.g. https://explorer.theqrl.org/a/Q010600af4216acb368a7cad4eefbe4f0b45da7d938fcd89e9e48707a38fce04a9e17d872ef8b2c). Navigate from page 1 to page 32 or later. After page 31 no more tx are shown. 412 tx done on this address but only 30*10 + 7 tx history shown. Token creation tx in earlier blocks are not loaded so no alt tokens shown in token balances tab.
Firefox & Chrome at least

**Comment by jplomas** [comment]
This seems to have been related to a problem with the gRPC node rather than the explorer itself.
