### ISSUE TITLE
Network Status Icon disparity between wallet/explorer

### ISSUE THREAD

**Issue by doctor-gonzo** [theQRL/block-explorer#38]
The green network status icon on the wallet sidebar makes perfect sense to me to indicate that the network is up, but on the explorer that same icon is white. If they were both green I think it would improve the sense of continuity between the two aspects of the site. 

![3](https://user-images.githubusercontent.com/32208642/37257453-004f2cda-2540-11e8-9f89-1491e2a4ac03.JPG)

It's a minor deal though - thanks for your great work on this. The explorer is getting better and better every time I use it

**Comment by scottdonaldau** [comment]
Thanks for reporting this @doctor-gonzo  We'll have it fixed up shortly.
