### ISSUE TITLE
Some transactions not showing for an address

### ISSUE THREAD

**Issue by som-dev** [theQRL/block-explorer#40]
This could be a qrl issue instead of a block-explorer issue but I will start here.
Testnet Feersum Endjinn. I am using the block explorer viewing address Q010600647bdcb1548622afa0a92ec1ba7b5d0fc212a3f2ae69fd830ac6ce01de5d94f1a66a7699 It shows only 2 transactions, a send of 99 quanta and a receive of a token. If I look at block 1774 and 2066 I see coinbase transactions to this address. There should be a lot more than 2 transactions for this address. https://explorer.theqrl.org/a/Q010600647bdcb1548622afa0a92ec1ba7b5d0fc212a3f2ae69fd830ac6ce01de5d94f1a66a7699
https://explorer.theqrl.org/block/1774
https://explorer.theqrl.org/block/2066

**Comment by cyyber** [comment]
The issue must be in the node with state. Thanks for reporting. I will look into the node.

**Comment by jplomas** [comment]
Confirmed node issue
