### ISSUE TITLE
Multisig vote addresses - state not found

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/block-explorer#406]
In reference to [PR #404](https://github.com/theQRL/block-explorer/pull/404), it looks like the problem might be related to Multisig vote addresses. 

Mutisig vote addresses are parsed by the explorer, but no state is found when you click on them. 

Here's some examples:

- [MULTISIG_VOTE Q1100007eb1794fddb6ed1fff476820d96d85e8c22f212ed0bb645c61ae957fea67d667f608c186](https://explorer.theqrl.org/tx/508fdf09b45bcbdd191f843fd1a46b7c1a5c677ce2de05ef8dd4d9b5621787f3)
- [MULTISIG_VOTE Q1100000d5eb382b865f1e72e0f4dd8fdb4bdcb2e8a10061af7f3ce441c7a758b8c5c1ea3c1eb89](https://explorer.theqrl.org/tx/c62237cae1705c03fa9d1105117ca098c9dcb245e2142a56f67ddbfc518e8599)
- [MULTISIG_VOTE Q110000f31c98e2c9f1268071dfa145d80ab094b35bf6001cbdcb83d4721410152c6e24b7be34d5](https://explorer.theqrl.org/tx/6ff91fdf563631f1de19e9fe847a303e38cd216ac90b653d6b96634fe4799264)

**Comment by jplomas** [comment]
Fixed in #407
