### ISSUE TITLE
Dollar value on transactions don't render the value, and instead NaN

### ISSUE THREAD

**Issue by jackalyst** [theQRL/block-explorer#415]
**Expected**

When viewing an address or transaction, for the dollar value to be emitted as a float in USD.

**Actual result**

Number shows as NaN

Screenshots.
![Screenshot from 2022-06-04 11-58-49](https://user-images.githubusercontent.com/232510/172019838-bc3ab127-6dc1-4ec4-be7c-c80a0318426b.png)
![Screenshot from 2022-06-04 11-58-39](https://user-images.githubusercontent.com/232510/172019839-c0183d59-9307-4477-8ada-ba330aad6a99.png)

Thanks for Kazanchev for notifying us of this issue in Telegram.

**Comment by jplomas** [comment]
Fixed in #416
