### ISSUE TITLE
Search function works for addresses but not always for TXs

### ISSUE THREAD

**Issue by doctor-gonzo** [theQRL/block-explorer#42]
I had a TX id copied to clipboard, and searching for it in the search bar did not result in any change of the page. Searching an address took me to the correct address page. Using Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

GIF: https://gfycat.com/ExcellentSnarlingBluebottlejellyfish

**Comment by jplomas** [comment]
Fixed in #43 

Thanks for reporting
