### ISSUE TITLE
Multi-sig address balance rounds up to whole amount

### ISSUE THREAD

**Issue by fr1t2** [theQRL/block-explorer#421]
When a balance in a multi-sig address is a decimal like `.999999999` quanta the explorer seems to be rounding up showing it as a whole. This bug can be seen with the following transactions:

Multi-sig address creation: https://testnet-explorer.theqrl.org/tx/91fcc1fd44e38d2601fbf247fe7b65c1831fbab969dbc4f779c0e18e6d700e4b

Transfer of `0.999999999` quanta to new multi-sig address: https://testnet-explorer.theqrl.org/tx/c9ee996f5757f40c27801a4c8fe34054b5f8007d6afd4ccfc1b9a6778b24840a

Multi-sig balance shown as `1.00000000` Quanta when it is actually `0.999999999`: https://testnet-explorer.theqrl.org/a/Q11000049f7908daaf5be55fdbfceffc9863865a66d26a86c4dcd3be491d9a065ecbe710e807b84

This appears to only be a bug in the explorer as the wallet and any transfer on-chain reflects the correct balance of `0.999999999`.

**Comment by jplomas** [comment]
Thanks for spotting and the detailed report.

This has been fixed on my branch.

PR and deployments in next 24hrs...
