### ISSUE TITLE
exlorer showing tx unconfirmed if link opened directly but shows confirmed if opened from the explorer latest transactions

### ISSUE THREAD

**Issue by Miner8912** [theQRL/block-explorer#8]
If I open up this link directly http://qrlexplorer.info/tx/d898dad2b1514e345b7180232fba3431d819dab6ffc5e6b1e6098ce4e246fbcc my transaction shows 0 confirmations, but if I look it up from the explorer page latest transactions it shows me 503+ confirmations?
![qrl2](https://user-images.githubusercontent.com/6080009/33528048-cc45dd90-d863-11e7-83da-8fc87a181b5d.jpg)

**Comment by jplomas** [comment]
Fixed in #9
