### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by danycoman** [theQRL/block-explorer#87]
Can you use it for other coins? I tried but not work. Anyway, look good, good luck!

**Comment by scottdonaldau** [comment]
Hey there @danycoman 

Thanks for the interest and kind comments about our block explorer!

It is only compatible with QRL, and there is no intention to make it work with other blockchain networks. You are free to fork the repo and update the server side elements to work with another chain if you choose however.

Best of luck!
Scott
